name: Perform Release
on:
  schedule:
    - cron:  '0 0 * * SUN'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create release version
        id: release
        run: echo "::set-output name=version::$(date +'%Y.%m.%d-%H%M%S')"
      - name: Count commits in last week
        id: commits
        run: echo "::set-output name=count::$(git rev-list --count HEAD --since='last Sunday')"
      - name: Set release version
        run: mvn --batch-mode versions:set -DnewVersion=${{ steps.release.outputs.version }} -DgenerateBackupPoms=false
      - name: Build with Maven
        run: mvn --batch-mode verify
      - name: Publish to GitHub Packages Apache Maven
        if: steps.commits.outputs.count > 0
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        if: steps.commits.outputs.count > 0
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.version }}
          release_name: Release ${{ steps.release.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Automated release, see [commits](https://github.com/metio/maven-build-process/commits/${{ steps.release.outputs.version }}) for changes.

            Use this project as a parent POM:
            ```xml
            <parent>
              <groupId>wtf.metio.maven.parents</groupId>
              <artifactId>maven-parents-java-[TYPE]</artifactId>
              <version>${{ steps.release.outputs.version }}</version>
            </parent>
            ```
            Replace `[TYPE]` with either `prototype` or `stable`.

            Use one (or all) of the provided BOMs:
            ```xml
            <dependencyManagement>
              <dependencies>
                <dependency>
                  <groupId>wtf.metio.maven.boms</groupId>
                  <artifactId>maven-boms-[TYPE]</artifactId>
                  <version>${{ steps.release.outputs.version }}</version>
                  <type>pom</type>
                  <scope>import</scope>
                </dependency>
              </dependencies>
            </dependencyManagement>
            ```
            Replace `[TYPE]` with one of the [available BOMs](https://github.com/metio/maven-build-process/tree/${{ steps.release.outputs.version }}/maven-boms).
