name: Perform Release
on:
  schedule:
    - cron:  15 1 * * FRI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create release version
        id: release
        run: echo "::set-output name=version::$(date +'%Y.%-m.%-d')"
      - name: Count commits in last week
        id: commits
        run: echo "::set-output name=count::$(git rev-list --count HEAD --since='last Friday')"
      - name: Set release version
        run: mvn --batch-mode versions:set -DnewVersion=${{ steps.release.outputs.version }} -DgenerateBackupPoms=false
      - id: gpg
        if: steps.commits.outputs.count > 0
        name: GPG Key
        run: echo "${{ secrets.GPG_SECRET_KEY_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/signing.key.asc
      - name: Publish to Maven Central
        if: steps.commits.outputs.count > 0
        run: mvn --batch-mode --activate-profiles release deploy -Dpgp.secretkey=keyfile:$GITHUB_WORKSPACE/signing.key.asc -Dpgp.passphrase=literal:${{ secrets.GPG_SECRET_KEY_PASSWORD }}
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      - name: Create Release
        if: steps.commits.outputs.count > 0
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.version }}
          release_name: ${{ steps.release.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Automated release, see [commits](https://github.com/metio/maven-build-process/commits/${{ steps.release.outputs.version }}) for changes.

            Use this project as a parent POM:
            ```xml
            <parent>
              <groupId>wtf.metio.maven.parents</groupId>
              <artifactId>maven-parents-java-[TYPE]</artifactId>
              <version>${{ steps.release.outputs.version }}</version>
            </parent>
            ```
            Replace `[TYPE]` with either `prototype` or `stable`.

            Use one (or all) of the provided BOMs:
            ```xml
            <dependencyManagement>
              <dependencies>
                <dependency>
                  <groupId>wtf.metio.maven.boms</groupId>
                  <artifactId>maven-boms-[TYPE]</artifactId>
                  <version>${{ steps.release.outputs.version }}</version>
                  <type>pom</type>
                  <scope>import</scope>
                </dependency>
              </dependencies>
            </dependencyManagement>
            ```
            Replace `[TYPE]` with one of the [available BOMs](https://github.com/metio/maven-build-process/tree/${{ steps.release.outputs.version }}/maven-boms).
      - name: Send Mail
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: release ${{ steps.release.outputs.version }}
          body: See https://github.com/metio/maven-build-process/releases/tag/${{ steps.release.outputs.version }} for details.
          to: maven-build-process@metio.groups.io
          from: ${{ secrets.MAIL_SENDER }}
      - id: matrix
        name: Send Matrix Message
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "release ${{ steps.release.outputs.version }} published - see https://github.com/metio/maven-build-process/releases/tag/${{ steps.release.outputs.version }} for details"
          server: "matrix.org"
