name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create release version
        id: release
        run: echo "::set-output name=version::$(date +'%Y.%-m.%-d')"
      - name: Count commits in last week
        id: commits
        run: echo "::set-output name=count::$(git rev-list --count HEAD --since='last Friday')"
      - name: Set release version
        run: mvn --batch-mode versions:set -DnewVersion=${{ steps.release.outputs.version }} -DgenerateBackupPoms=false
      - id: gpg
        name: GPG Key
        run: echo "${{ secrets.GPG_KEY }}" | base64 --decode > $GITHUB_WORKSPACE/signing.key.asc
      - name: Build with Maven
        run: mvn --batch-mode verify -Dpgp.secretkey=keyfile:$GITHUB_WORKSPACE/signing.key.asc -Dpgp.passphrase=literal:${{ secrets.GPG_KEY_PASSPHRASE }}
      - name: Publish to Maven Central
        if: steps.commits.outputs.count > 0
        run: mvn --batch-mode deploy -Dpgp.secretkey=keyfile:$GITHUB_WORKSPACE/signing.key.asc -Dpgp.passphrase=literal:${{ secrets.GPG_KEY_PASSPHRASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      - name: Create Release
        if: steps.commits.outputs.count > 0
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.version }}
          release_name: Release ${{ steps.release.outputs.version }}
          draft: false
          prerelease: false
          body: |
            Automated release, see [commits](https://github.com/metio/maven-build-process/commits/${{ steps.release.outputs.version }}) for changes.

            Use this project as a parent POM:
            ```xml
            <parent>
              <groupId>wtf.metio.maven.parents</groupId>
              <artifactId>maven-parents-java-[TYPE]</artifactId>
              <version>${{ steps.release.outputs.version }}</version>
            </parent>
            ```
            Replace `[TYPE]` with either `prototype` or `stable`.

            Use one (or all) of the provided BOMs:
            ```xml
            <dependencyManagement>
              <dependencies>
                <dependency>
                  <groupId>wtf.metio.maven.boms</groupId>
                  <artifactId>maven-boms-[TYPE]</artifactId>
                  <version>${{ steps.release.outputs.version }}</version>
                  <type>pom</type>
                  <scope>import</scope>
                </dependency>
              </dependencies>
            </dependencyManagement>
            ```
            Replace `[TYPE]` with one of the [available BOMs](https://github.com/metio/maven-build-process/tree/${{ steps.release.outputs.version }}/maven-boms).
      - name: Send Mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: release ${{ steps.release.outputs.version }}
          body: See https://github.com/metio/maven-build-process/releases/tag/${{ steps.release.outputs.version }} for details.
          to: maven-build-process@metio.groups.io
          from: ${{ secrets.MAIL_SENDER }}
