name: Update Dependencies
on:
  schedule:
    - cron:  0 0 * * THU
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: update
        name: Update properties
        run: mvn --batch-mode --update-snapshots versions:update-properties -DgenerateBackupPoms=false
      - id: changes
        name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub <noreply@github.com>
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: Update properties to latest version
          add: "['pom.xml', '*/pom.xml']"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
