name: update dependencies
on:
  schedule:
    - cron:  '0 0 * * SAT'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Update properties
        run: mvn --batch-mode --update-snapshots versions:update-properties -DgenerateBackupPoms=false
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update properties to latest version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Update properties to latest version'
          body: |
            `mvn --batch-mode --update-snapshots versions:update-properties -DgenerateBackupPoms=false`
          labels: enhancement
          assignees: sebhoss
          draft: false
          branch: update-properties
